- project:
    templates:
      - openstack-python-jobs
      - openstack-python35-jobs
      - publish-openstack-docs-pti
      - check-requirements
      - periodic-stable-jobs
      - release-notes-jobs
    check:
      jobs:
        - murano-congress-devstack
        - murano-rally-task
        - murano-tempest-api
        - murano-tempest-cfapi
        - openstack-tox-lower-constraints
        - openstack-tox-cover:
            voting: false
    gate:
      queue: murano
      jobs:
        - murano-tempest-api
        - openstack-tox-lower-constraints
    experimental:
      jobs:
        - murano-functional

    post:
      jobs:
        - openstack-tox-cover
- job:
    name: murano-congress-devstack
    parent: murano-tempest-base
    voting: false
    timeout: 4200
    irrelevant-files:
      - ^(test-|)requirements.txt$
      - ^setup.cfg$
      - ^doc/.*$
      - ^.*\.rst$
      - ^releasenotes/.*$
      - ^murano/tests/.*$
    required-projects:
      - openstack/congress
      - openstack/congress-dashboard
      - openstack/mistral
      - openstack/mistral-dashboard
      - openstack/python-congressclient
      - openstack/python-heatclient
      - openstack/python-mistralclient
      - openstack/python-muranoclient
    vars:
      devstack_services:
        tls-proxy: false
      devstack_localrc:
        MURANO_ENABLE_MODEL_POLICY_ENFORCEMENT: true
      devstack_plugins:
        congress: https://opendev.org/openstack/congress
        mistral: https://opendev.org/openstack/mistral
      tempest_test_regex: functional

- job:
    name: murano-rally-task
    parent: rally-task-murano
    timeout: 7800
    vars:
      devstack_plugins:
        rally-openstack: https://opendev.org/openstack/rally-openstack
      rally_task: rally-jobs/task-murano.yaml
    required-projects:
      - openstack/rally-openstack

- job:
    name: murano-tempest-base
    parent: devstack-tempest
    irrelevant-files:
      - ^(test-|)requirements.txt$
      - ^setup.cfg$
      - ^doc/.*$
      - ^.*\.rst$
      - ^releasenotes/.*$
      - ^murano/tests/.*$
    timeout: 7800
    required-projects:
      - openstack/heat
      - openstack/murano
      - openstack/murano-dashboard
      - openstack/python-heatclient
      - openstack/python-muranoclient
      - openstack/tempest
      - openstack/murano-tempest-plugin
    vars:
      devstack_plugins:
        murano: https://opendev.org/openstack/murano
        heat: https://opendev.org/openstack/heat
      devstack_services:
        tempest: true
        s-account: false
        s-container: false
        s-object: false
        s-proxy: false
        tls-proxy: false
      devstack_localrc:
        TEMPEST_PLUGINS: "'{{ ansible_user_dir }}/src/opendev.org/openstack/murano-tempest-plugin'"
      tempest_test_regex: application_catalog
      tox_envlist: all

- job:
    name: murano-tempest-api
    parent: murano-tempest-base

- job:
    name: murano-tempest-cfapi
    parent: murano-tempest-base
    voting: false
    vars:
      devstack_services:
        murano-cfapi: true
      tempest_test_regex: service_broker

- job:
    name: murano-functional
    parent: legacy-dsvm-base
    run: playbooks/legacy/murano-dsvm-functional/run.yaml
    post-run: playbooks/legacy/murano-dsvm-functional/post.yaml
    timeout: 7800
    required-projects:
      - openstack/devstack-gate
      - openstack/heat
      - openstack/murano
      - openstack/murano-dashboard
      - openstack/python-heatclient
      - openstack/python-muranoclient
