- project:
    check:
      jobs:
        - murano-congress-devstack
        - murano-rally-task
        - murano-tempest-api
        - murano-tempest-cfapi
        - openstack-tox-lower-constraints
    gate:
      jobs:
        - murano-tempest-api
        - openstack-tox-lower-constraints
    experimental:
      jobs:
        - murano-functional

- job:
    name: murano-congress-devstack
    parent: legacy-dsvm-base
    run: playbooks/legacy/murano-congress-devstack-dsvm/run.yaml
    post-run: playbooks/legacy/murano-congress-devstack-dsvm/post.yaml
    voting: false
    timeout: 4200
    required-projects:
      - openstack-dev/devstack
      - openstack-infra/devstack-gate
      - openstack/congress
      - openstack/congress-dashboard
      - openstack/heat
      - openstack/mistral
      - openstack/mistral-dashboard
      - openstack/murano
      - openstack/murano-dashboard
      - openstack/python-congressclient
      - openstack/python-heatclient
      - openstack/python-mistralclient
      - openstack/python-muranoclient

- job:
    name: murano-rally-task
    parent: rally-task-murano
    timeout: 7800
    vars:
      devstack_plugins:
        rally-openstack: https://git.openstack.org/openstack/rally-openstack
      rally_task: rally-jobs/task-murano.yaml
    required-projects:
      - openstack/rally-openstack

- job:
    name: murano-tempest-api
    parent: legacy-dsvm-base
    run: playbooks/legacy/tempest-dsvm-murano-api/run.yaml
    post-run: playbooks/legacy/tempest-dsvm-murano-api/post.yaml
    irrelevant-files:
      - ^(test-|)requirements.txt$
      - ^setup.cfg$
      - ^doc/.*$
      - ^.*\.rst$
      - ^releasenotes/.*$
      - ^murano/tests/.*$
    timeout: 7800
    required-projects:
      - openstack-infra/devstack-gate
      - openstack/heat
      - openstack/murano
      - openstack/murano-dashboard
      - openstack/python-heatclient
      - openstack/python-muranoclient
      - openstack/tempest
      - openstack/murano-tempest-plugin

- job:
    name: murano-tempest-cfapi
    parent: legacy-dsvm-base
    run: playbooks/legacy/tempest-dsvm-murano-cfapi/run.yaml
    post-run: playbooks/legacy/tempest-dsvm-murano-cfapi/post.yaml
    voting: false
    irrelevant-files:
      - ^(test-|)requirements.txt$
      - ^setup.cfg$
      - ^doc/.*$
      - ^.*\.rst$
      - ^releasenotes/.*$
      - ^murano/tests/.*$
    timeout: 7800
    required-projects:
      - openstack-infra/devstack-gate
      - openstack/heat
      - openstack/murano
      - openstack/murano-dashboard
      - openstack/python-heatclient
      - openstack/python-muranoclient
      - openstack/tempest
      - openstack/murano-tempest-plugin

- job:
    name: murano-functional
    parent: legacy-dsvm-base
    run: playbooks/legacy/murano-dsvm-functional/run.yaml
    post-run: playbooks/legacy/murano-dsvm-functional/post.yaml
    timeout: 7800
    required-projects:
      - openstack-infra/devstack-gate
      - openstack/heat
      - openstack/murano
      - openstack/murano-dashboard
      - openstack/python-heatclient
      - openstack/python-muranoclient
